window.esdocSearchIndex = [
  [
    "typography-fixer/src/typography-fixer.js~check",
    "function/index.html#static-function-check",
    "<span>check</span> <span class=\"search-result-import-path\">typography-fixer/src/typography-fixer.js</span>",
    "function"
  ],
  [
    "typography-fixer/src/rules/en-uk/index.js~enuk",
    "variable/index.html#static-variable-enUK",
    "<span>enUK</span> <span class=\"search-result-import-path\">typography-fixer/src/rules/en-UK/index.js</span>",
    "variable"
  ],
  [
    "typography-fixer/src/rules/en-uk/html.js~enuk_html",
    "variable/index.html#static-variable-enUK_HTML",
    "<span>enUK_HTML</span> <span class=\"search-result-import-path\">typography-fixer/src/rules/en-UK/html.js</span>",
    "variable"
  ],
  [
    "typography-fixer/src/rules/es-es/index.js~eses",
    "variable/index.html#static-variable-esES",
    "<span>esES</span> <span class=\"search-result-import-path\">typography-fixer/src/rules/es-ES/index.js</span>",
    "variable"
  ],
  [
    "typography-fixer/src/typography-fixer.js~fix",
    "function/index.html#static-function-fix",
    "<span>fix</span> <span class=\"search-result-import-path\">typography-fixer/src/typography-fixer.js</span>",
    "function"
  ],
  [
    "typography-fixer/src/rules/fr-fr/index.js~frfr",
    "variable/index.html#static-variable-frFR",
    "<span>frFR</span> <span class=\"search-result-import-path\">typography-fixer/src/rules/fr-FR/index.js</span>",
    "variable"
  ],
  [
    "typography-fixer/src/rules/fr-fr/html.js~frfr_html",
    "variable/index.html#static-variable-frFR_HTML",
    "<span>frFR_HTML</span> <span class=\"search-result-import-path\">typography-fixer/src/rules/fr-FR/html.js</span>",
    "variable"
  ],
  [
    "typography-fixer/src/rules/fractions.js~fractions",
    "variable/index.html#static-variable-fractions",
    "<span>fractions</span> <span class=\"search-result-import-path\">typography-fixer/src/rules/fractions.js</span>",
    "variable"
  ],
  [
    "typography-fixer/src/typography-fixer.js~group",
    "function/index.html#static-function-group",
    "<span>group</span> <span class=\"search-result-import-path\">typography-fixer/src/typography-fixer.js</span>",
    "function"
  ],
  [
    "typography-fixer/src/rules/html.js~html",
    "variable/index.html#static-variable-html",
    "<span>html</span> <span class=\"search-result-import-path\">typography-fixer/src/rules/html.js</span>",
    "variable"
  ],
  [
    "typography-fixer/src/ignores/html.js~htmlignores",
    "variable/index.html#static-variable-htmlIgnores",
    "<span>htmlIgnores</span> <span class=\"search-result-import-path\">typography-fixer/src/ignores/html.js</span>",
    "variable"
  ],
  [
    "typography-fixer/src/typography-fixer.js~ignore",
    "function/index.html#static-function-ignore",
    "<span>ignore</span> <span class=\"search-result-import-path\">typography-fixer/src/typography-fixer.js</span>",
    "function"
  ],
  [
    "typography-fixer/src/rules/line-breaks.js~linebreaks",
    "variable/index.html#static-variable-lineBreaks",
    "<span>lineBreaks</span> <span class=\"search-result-import-path\">typography-fixer/src/rules/line-breaks.js</span>",
    "variable"
  ],
  [
    "typography-fixer/src/ignores/markdown.js~markdownignores",
    "variable/index.html#static-variable-markdownIgnores",
    "<span>markdownIgnores</span> <span class=\"search-result-import-path\">typography-fixer/src/ignores/markdown.js</span>",
    "variable"
  ],
  [
    "typography-fixer/src/rules/punctuations.js~punctuations",
    "variable/index.html#static-variable-punctuations",
    "<span>punctuations</span> <span class=\"search-result-import-path\">typography-fixer/src/rules/punctuations.js</span>",
    "variable"
  ],
  [
    "typography-fixer/src/typography-fixer.js~rule",
    "function/index.html#static-function-rule",
    "<span>rule</span> <span class=\"search-result-import-path\">typography-fixer/src/typography-fixer.js</span>",
    "function"
  ],
  [
    "typography-fixer/src/rules/symbols.js~symbols",
    "variable/index.html#static-variable-symbols",
    "<span>symbols</span> <span class=\"search-result-import-path\">typography-fixer/src/rules/symbols.js</span>",
    "variable"
  ],
  [
    "typography-fixer/src/rules/units.js~units",
    "variable/index.html#static-variable-units",
    "<span>units</span> <span class=\"search-result-import-path\">typography-fixer/src/rules/units.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/constants.js",
    "file/src/constants.js.html",
    "src/constants.js",
    "file"
  ],
  [
    "src/ignores/html.js",
    "file/src/ignores/html.js.html",
    "src/ignores/html.js",
    "file"
  ],
  [
    "src/ignores/markdown.js",
    "file/src/ignores/markdown.js.html",
    "src/ignores/markdown.js",
    "file"
  ],
  [
    "src/lowercase.js",
    "file/src/lowercase.js.html",
    "src/lowercase.js",
    "file"
  ],
  [
    "src/rules/en-uk/html.js",
    "file/src/rules/en-UK/html.js.html",
    "src/rules/en-UK/html.js",
    "file"
  ],
  [
    "src/rules/en-uk/index.js",
    "file/src/rules/en-UK/index.js.html",
    "src/rules/en-UK/index.js",
    "file"
  ],
  [
    "src/rules/es-es/index.js",
    "file/src/rules/es-ES/index.js.html",
    "src/rules/es-ES/index.js",
    "file"
  ],
  [
    "src/rules/fr-fr/html.js",
    "file/src/rules/fr-FR/html.js.html",
    "src/rules/fr-FR/html.js",
    "file"
  ],
  [
    "src/rules/fr-fr/index.js",
    "file/src/rules/fr-FR/index.js.html",
    "src/rules/fr-FR/index.js",
    "file"
  ],
  [
    "src/rules/fractions.js",
    "file/src/rules/fractions.js.html",
    "src/rules/fractions.js",
    "file"
  ],
  [
    "src/rules/html.js",
    "file/src/rules/html.js.html",
    "src/rules/html.js",
    "file"
  ],
  [
    "src/rules/line-breaks.js",
    "file/src/rules/line-breaks.js.html",
    "src/rules/line-breaks.js",
    "file"
  ],
  [
    "src/rules/punctuations.js",
    "file/src/rules/punctuations.js.html",
    "src/rules/punctuations.js",
    "file"
  ],
  [
    "src/rules/symbols.js",
    "file/src/rules/symbols.js.html",
    "src/rules/symbols.js",
    "file"
  ],
  [
    "src/rules/units.js",
    "file/src/rules/units.js.html",
    "src/rules/units.js",
    "file"
  ],
  [
    "src/typography-fixer.js",
    "file/src/typography-fixer.js.html",
    "src/typography-fixer.js",
    "file"
  ],
  [
    "src/uppercase.js",
    "file/src/uppercase.js.html",
    "src/uppercase.js",
    "file"
  ]
]